### ISSUE TITLE
I have a question about my tensorboardX

### ISSUE THREAD

**Issue by JaxferZ** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#108]
hi, @tensorboy ,when I run the train_VGG19.py, I met the following error:
Traceback (most recent call last):
  File "train_VGG19.py", line 304, in <module>
    writer = SummaryWriter(log_dir=args.logdir)       
  File "/home/lin/anaconda3/lib/python3.7/site-packages/tensorboardX/writer.py", line 257, in __init__
    self._get_file_writer()
  File "/home/lin/anaconda3/lib/python3.7/site-packages/tensorboardX/writer.py", line 321, in _get_file_writer
    **self.kwargs)
  File "/home/lin/anaconda3/lib/python3.7/site-packages/tensorboardX/writer.py", line 93, in __init__
    logdir, max_queue, flush_secs, filename_suffix)
  File "/home/lin/anaconda3/lib/python3.7/site-packages/tensorboardX/event_file_writer.py", line 104, in __init__
    directory_check(self._logdir)
  File "/home/lin/anaconda3/lib/python3.7/site-packages/tensorboardX/record_writer.py", line 44, in directory_check
    os.makedirs(path)
  File "/home/lin/anaconda3/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/lin/anaconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/extra'

**Comment by tensorboy** [comment]
You can change that directory `/extra` to your local directory.
