### ISSUE TITLE
The following error occurred when I tested my trained model.

### ISSUE THREAD

**Issue by Freezing-hxy** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#145]
(sort2) hxy@uac516:~/Desktop/anomaly_detection/pytorch_Realtime_Multi-Person_Pose_Estimation$ python demo/picture_demo.py
Bulding VGG19
Traceback (most recent call last):
  File "demo/picture_demo.py", line 46, in <module>
    model.load_state_dict(torch.load(args.weight))
  File "/home/hxy/anaconda3/envs/sort2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for rtpose_model:
        Missing key(s) in state_dict: "model0.0.weight", "model0.0.bias", "model0.2.weight", "model0.2.bias", "model0.5.weight", "model0.5.bias", "model0.7.weight", "model0.7.bias", "model0.10.weight", "model0.10.bias", "model0.12.weight", "model0.12.bias", "model0.14.weight", "model0.14.bias", "model0.16.weight", "model0.16.bias", "model0.19.weight", "model0.19.bias", "model0.21.weight", "model0.21.bias", "model0.23.weight", "model0.23.bias", "model0.25.weight", "model0.25.bias", "model1_1.0.weight", "model1_1.0.bias", "model1_1.2.weight", "model1_1.2.bias", "model1_1.4.weight", "model1_1.4.bias", "model1_1.6.weight", "model1_1.6.bias", "model1_1.8.weight", "model1_1.8.bias", "model2_1.0.weight", "model2_1.0.bias", "model2_1.2.weight", "model2_1.2.bias", "model2_1.4.weight", "model2_1.4.bias", "model2_1.6.weight", "model2_1.6.bias", "model2_1.8.weight", "model2_1.8.bias", "model2_1.10.weight", "model2_1.10.bias", "model2_1.12.weight", "model2_1.12.bias", "model3_1.0.weight", "model3_1.0.bias", "model3_1.2.weight", "model3_1.2.bias", "model3_1.4.weight", "model3_1.4.bias", "model3_1.6.weight", "model3_1.6.bias", "model3_1.8.weight", "model3_1.8.bias", "model3_1.10.weight", "model3_1.10.bias", "model3_1.12.weight", "model3_1.12.bias", "model4_1.0.weight", "model4_1.0.bias", "model4_1.2.weight", "model4_1.2.bias", "model4_1.4.weight", "model4_1.4.bias", "model4_1.6.weight", "model4_1.6.bias", "model4_1.8.weight", "model4_1.8.bias", "model4_1.10.weight", "model4_1.10.bias", "model4_1.12.weight", "model4_1.12.bias", "model5_1.0.weight", "model5_1.0.bias", "model5_1.2.weight", "model5_1.2.bias", "model5_1.4.weight", "model5_1.4.bias", "model5_1.6.weight", "model5_1.6.bias", "model5_1.8.weight", "model5_1.8.bias", "model5_1.10.weight", "model5_1.10.bias", "model5_1.12.weight", "model5_1.12.bias", "model6_1.0.weight", "model6_1.0.bias", "model6_1.2.weight", "model6_1.2.bias", "model6_1.4.weight", "model6_1.4.bias", "model6_1.6.weight", "model6_1.6.bias", "model6_1.8.weight", "model6_1.8.bias", "model6_1.10.weight", "model6_1.10.bias", "model6_1.12.weight", "model6_1.12.bias", "model1_2.0.weight", "model1_2.0.bias", "model1_2.2.weight", "model1_2.2.bias", "model1_2.4.weight", "model1_2.4.bias", "model1_2.6.weight", "model1_2.6.bias", "model1_2.8.weight", "model1_2.8.bias", "model2_2.0.weight", "model2_2.0.bias", "model2_2.2.weight", "model2_2.2.bias", "model2_2.4.weight", "model2_2.4.bias", "model2_2.6.weight", "model2_2.6.bias", "model2_2.8.weight", "model2_2.8.bias", "model2_2.10.weight", "model2_2.10.bias", "model2_2.12.weight", "model2_2.12.bias", "model3_2.0.weight", "model3_2.0.bias", "model3_2.2.weight", "model3_2.2.bias", "model3_2.4.weight", "model3_2.4.bias", "model3_2.6.weight", "model3_2.6.bias", "model3_2.8.weight", "model3_2.8.bias", "model3_2.10.weight", "model3_2.10.bias", "model3_2.12.weight", "model3_2.12.bias", "model4_2.0.weight", "model4_2.0.bias", "model4_2.2.weight", "model4_2.2.bias", "model4_2.4.weight", "model4_2.4.bias", "model4_2.6.weight", "model4_2.6.bias", "model4_2.8.weight", "model4_2.8.bias", "model4_2.10.weight", "model4_2.10.bias", "model4_2.12.weight", "model4_2.12.bias", "model5_2.0.weight", "model5_2.0.bias", "model5_2.2.weight", "model5_2.2.bias", "model5_2.4.weight", "model5_2.4.bias", "model5_2.6.weight", "model5_2.6.bias", "model5_2.8.weight", "model5_2.8.bias", "model5_2.10.weight", "model5_2.10.bias", "model5_2.12.weight", "model5_2.12.bias", "model6_2.0.weight", "model6_2.0.bias", "model6_2.2.weight", "model6_2.2.bias", "model6_2.4.weight", "model6_2.4.bias", "model6_2.6.weight", "model6_2.6.bias", "model6_2.8.weight", "model6_2.8.bias", "model6_2.10.weight", "model6_2.10.bias", "model6_2.12.weight", "model6_2.12.bias".
        Unexpected key(s) in state_dict: "module.model0.0.weight", "module.model0.0.bias", "module.model0.2.weight", "module.model0.2.bias", "module.model0.5.weight", "module.model0.5.bias", "module.model0.7.weight", "module.model0.7.bias", "module.model0.10.weight", "module.model0.10.bias", "module.model0.12.weight", "module.model0.12.bias", "module.model0.14.weight", "module.model0.14.bias", "module.model0.16.weight", "module.model0.16.bias", "module.model0.19.weight", "module.model0.19.bias", "module.model0.21.weight", "module.model0.21.bias", "module.model0.23.weight", "module.model0.23.bias", "module.model0.25.weight", "module.model0.25.bias", "module.model1_1.0.weight", "module.model1_1.0.bias", "module.model1_1.2.weight", "module.model1_1.2.bias", "module.model1_1.4.weight", "module.model1_1.4.bias", "module.model1_1.6.weight", "module.model1_1.6.bias", "module.model1_1.8.weight", "module.model1_1.8.bias", "module.model2_1.0.weight", "module.model2_1.0.bias", "module.model2_1.2.weight", "module.model2_1.2.bias", "module.model2_1.4.weight", "module.model2_1.4.bias", "module.model2_1.6.weight", "module.model2_1.6.bias", "module.model2_1.8.weight", "module.model2_1.8.bias", "module.model2_1.10.weight", "module.model2_1.10.bias", "module.model2_1.12.weight", "module.model2_1.12.bias", "module.model3_1.0.weight", "module.model3_1.0.bias", "module.model3_1.2.weight", "module.model3_1.2.bias", "module.model3_1.4.weight", "module.model3_1.4.bias", "module.model3_1.6.weight", "module.model3_1.6.bias", "module.model3_1.8.weight", "module.model3_1.8.bias", "module.model3_1.10.weight", "module.model3_1.10.bias", "module.model3_1.12.weight", "module.model3_1.12.bias", "module.model4_1.0.weight", "module.model4_1.0.bias", "module.model4_1.2.weight", "module.model4_1.2.bias", "module.model4_1.4.weight", "module.model4_1.4.bias", "module.model4_1.6.weight", "module.model4_1.6.bias", "module.model4_1.8.weight", "module.model4_1.8.bias", "module.model4_1.10.weight", "module.model4_1.10.bias", "module.model4_1.12.weight", "module.model4_1.12.bias", "module.model5_1.0.weight", "module.model5_1.0.bias", "module.model5_1.2.weight", "module.model5_1.2.bias", "module.model5_1.4.weight", "module.model5_1.4.bias", "module.model5_1.6.weight", "module.model5_1.6.bias", "module.model5_1.8.weight", "module.model5_1.8.bias", "module.model5_1.10.weight", "module.model5_1.10.bias", "module.model5_1.12.weight", "module.model5_1.12.bias", "module.model6_1.0.weight", "module.model6_1.0.bias", "module.model6_1.2.weight", "module.model6_1.2.bias", "module.model6_1.4.weight", "module.model6_1.4.bias", "module.model6_1.6.weight", "module.model6_1.6.bias", "module.model6_1.8.weight", "module.model6_1.8.bias", "module.model6_1.10.weight", "module.model6_1.10.bias", "module.model6_1.12.weight", "module.model6_1.12.bias", "module.model1_2.0.weight", "module.model1_2.0.bias", "module.model1_2.2.weight", "module.model1_2.2.bias", "module.model1_2.4.weight", "module.model1_2.4.bias", "module.model1_2.6.weight", "module.model1_2.6.bias", "module.model1_2.8.weight", "module.model1_2.8.bias", "module.model2_2.0.weight", "module.model2_2.0.bias", "module.model2_2.2.weight", "module.model2_2.2.bias", "module.model2_2.4.weight", "module.model2_2.4.bias", "module.model2_2.6.weight", "module.model2_2.6.bias", "module.model2_2.8.weight", "module.model2_2.8.bias", "module.model2_2.10.weight", "module.model2_2.10.bias", "module.model2_2.12.weight", "module.model2_2.12.bias", "module.model3_2.0.weight", "module.model3_2.0.bias", "module.model3_2.2.weight", "module.model3_2.2.bias", "module.model3_2.4.weight", "module.model3_2.4.bias", "module.model3_2.6.weight", "module.model3_2.6.bias", "module.model3_2.8.weight", "module.model3_2.8.bias", "module.model3_2.10.weight", "module.model3_2.10.bias", "module.model3_2.12.weight", "module.model3_2.12.bias", "module.model4_2.0.weight", "module.model4_2.0.bias", "module.model4_2.2.weight", "module.model4_2.2.bias", "module.model4_2.4.weight", "module.model4_2.4.bias", "module.model4_2.6.weight", "module.model4_2.6.bias", "module.model4_2.8.weight", "module.model4_2.8.bias", "module.model4_2.10.weight", "module.model4_2.10.bias", "module.model4_2.12.weight", "module.model4_2.12.bias", "module.model5_2.0.weight", "module.model5_2.0.bias", "module.model5_2.2.weight", "module.model5_2.2.bias", "module.model5_2.4.weight", "module.model5_2.4.bias", "module.model5_2.6.weight", "module.model5_2.6.bias", "module.model5_2.8.weight", "module.model5_2.8.bias", "module.model5_2.10.weight", "module.model5_2.10.bias", "module.model5_2.12.weight", "module.model5_2.12.bias", "module.model6_2.0.weight", "module.model6_2.0.bias", "module.model6_2.2.weight", "module.model6_2.2.bias", "module.model6_2.4.weight", "module.model6_2.4.bias", "module.model6_2.6.weight", "module.model6_2.6.bias", "module.model6_2.8.weight", "module.model6_2.8.bias", "module.model6_2.10.weight", "module.model6_2.10.bias", "module.model6_2.12.weight", "module.model6_2.12.bias".

**Comment by thisimyusername** [comment]
now I meet same error，

**Comment by chris2lee** [comment]
I think you  downloaded  a wrong weight.
