### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by chm826017** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#20]
My pytorch version is 0.2.0_3.  I have come across the problem:
Traceback (most recent call last):
  File "convert.py", line 11, in <module>
    import caffe
  File "/home/sensenets/anaconda2/lib/python2.7/site-packages/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/home/sensenets/anaconda2/lib/python2.7/site-packages/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: dlopen: cannot load any more object with static TLS
could you kindly help?

**Comment by tensorboy** [comment]
It is a caffe problem, right?

**Comment by 1LOVESJohnny** [comment]
Hi, have you solved the problem? May you tell me the solution?
