### ISSUE TITLE
Compatibility with python 3

### ISSUE THREAD

**Issue by herleeyandi** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#37]
I have tried to make the code run-able in python 3.6.
- Use `print()`
- Change `.iteritems()` with `.items()`
However I got the last error

```
Traceback (most recent call last):
  File "convert.py", line 73, in <module>
    models[k] = make_layers(v)
  File "convert.py", line 53, in make_layers
    k = one_[0]
TypeError: 'dict_keys' object does not support indexing
```
How to solve this?

**Comment by herleeyandi** [comment]
solved by adding `list([some variable].items())`
line 52 `one_ = list(cfg_dict[-1].keys())`
line 210 and 211
```
output1_ = net.blobs[list(output_blobs.keys())[0]].data
output2_ = net.blobs[list(output_blobs.keys())[1]].data
```
But again I have this error.
```
Traceback (most recent call last):
  File "convert.py", line 217, in <module>
    print('output1 have %10.10f%% relative error'%(np.linalg.norm(output1-output1_)/np.linalg.norm(output1_)*100))
ValueError: operands could not be broadcast together with shapes (1,38,23,25) (1,19,23,25)
```

**Comment by tensorboy** [comment]
Updated and it Compatible with python3 now. :)
