### ISSUE TITLE
train_VGG19.py error

### ISSUE THREAD

**Issue by sobesshi** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#47]
python train_VGG19.py --json_path training/dataset/COCO.json --data_dir training/dataset/COCO/images --mask_dir training/dataset/COCO

Loading dataset...
train dataset len: 121522
val dataset len: 4873
Bulding VGG19
load imagenet pretrained model: ./network/weight/
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /install_opencv/opencv-3.3.0/modules/imgproc/src/imgwarp.cpp, line 3483
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /install_opencv/opencv-3.3.0/modules/imgproc/src/imgwarp.cpp, line 3483
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /install_opencv/opencv-3.3.0/modules/imgproc/src/imgwarp.cpp, line 3483
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /install_opencv/opencv-3.3.0/modules/imgproc/src/imgwarp.cpp, line 3483
Traceback (most recent call last):
  File "train_VGG19.py", line 310, in <module>
    train_loss = train(train_data, model, optimizer, epoch)
  File "train_VGG19.py", line 157, in train
    for i, (img, heatmap_target, heat_mask, paf_target, paf_mask) in enumerate(train_loader):
  File "anaconda3/envs/py35/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "anaconda3/envs/py35/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
cv2.error: Traceback (most recent call last):
  File "anaconda3/envs/py35/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "anaconda3/envs/py35/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "pytorch_Realtime_Multi-Person_Pose_Estimation/training/datasets/coco_data/COCO_data_pipeline.py", line 238, in __getitem__
    meta_data, img, mask_miss, self.params_transform)
  File "pytorch_Realtime_Multi-Person_Pose_Estimation/training/datasets/coco_data/ImageAugmentation.py", line 42, in aug_scale
    fy=scale, interpolation=cv2.INTER_CUBIC)
cv2.error: /install_opencv/opencv-3.3.0/modules/imgproc/src/imgwarp.cpp:3483: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize

**Comment by tensorboy** [comment]
It may caused by some path problem: https://stackoverflow.com/questions/47172770/error-215-ssize-width-0-ssize-height-0-in-function-resize

**Comment by sobesshi** [comment]
print(self.root + 'mask2014/val2014_mask_miss_' + img_idx + 'png')

printed ./training/dataset/COCO/images/mask2014/val2014_mask_miss_000000004947.png

ls ./training/dataset/COCO/images/mask2014/val2014_mask_miss_000000113970.png
ls: cannot access './training/dataset/COCO/images/mask2014/val2014_mask_miss_000000113970.png': No such file or directory

Filenames may be different?
mask2014 position is correct.
In mask2014, images are jpg.

**Comment by sobesshi** [comment]
After change
self.mask_dir + 'mask2014/val2014_mask_miss_' + img_idx + 'png', 0)
to
self.mask_dir + 'mask2014/val2014/mask_COCO_val2014_' + img_idx + 'jpg', 0),

Error codes changed.

Loading dataset...
train dataset len: 121522
val dataset len: 4873
Bulding VGG19
load imagenet pretrained model: ./network/weight/
./training/dataset/COCO/images/mask2014/train2014/mask_COCO_train2014_000000010094.jpg
...
Traceback (most recent call last):
  File "train_VGG19.py", line 310, in <module>
    train_loss = train(train_data, model, optimizer, epoch)
  File "train_VGG19.py", line 157, in train
    for i, (img, heatmap_target, heat_mask, paf_target, paf_mask) in enumerate(train_loader):
  File "anaconda3/envs/py35/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "anaconda3/envs/py35/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n  File "anaconda3/envs/py35/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "anaconda3/envs/py35/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "pytorch_Realtime_Multi-Person_Pose_Estimation/training/datasets/coco_data/COCO_data_pipeline.py", line 255, in __getitem__\n    meta_data, mask_miss)\n  File "pytorch_Realtime_Multi-Person_Pose_Estimation/training/datasets/coco_data/COCO_data_pipeline.py", line 214, in get_ground_truth\n    count=count, params_transform=self.params_transform)\n  File "pytorch_Realtime_Multi-Person_Pose_Estimation/training/datasets/coco_data/paf.py", line 27, in putVecMaps\n    thre = params_transform[\'limb_width\']   # limb width\nKeyError: \'limb_width\'\n'

**Comment by sobesshi** [comment]
It worked!

You forgot to define "params_transform['limb_width'] = 1.289" in train_VGG19.py

**Comment by tensorboy** [comment]
I remember it is 1 for VGG19 and 1.289 for stackedhourglass，that number should be different based on the size of output.
I used this method to test best sigma and limb_width for heatmap and pad:
Using different sigma and limb_width to generate ground truth heatmap and paf to see which value has the highest mAP on validation set.
