### ISSUE TITLE
evaluation.py error

### ISSUE THREAD

**Issue by sobesshi** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#52]
python evaluation.py  using pose_model.pth(via rtpose original link https://www.dropbox.com/s/ae071mfm2qoyc8v/pose_model.pth?dl=0)

Traceback (most recent call last):
  File "evaluation.py", line 34, in <module>
    model=model, preprocess='vgg')
  File "../evaluate/coco_eval.py", line 311, in run_eval
    return eval_coco(outputs=outputs, dataDir=anno_dir, imgIds=img_ids)
  File "../evaluate/coco_eval.py", line 50, in eval_coco
    json.dump(outputs, f)  
  File "/home/anaconda3/envs/py35/lib/python3.5/json/__init__.py", line 178, in dump
    for chunk in iterable:
  File "/home/anaconda3/envs/py35/lib/python3.5/json/encoder.py", line 427, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/home/anaconda3/envs/py35/lib/python3.5/json/encoder.py", line 324, in _iterencode_list
    yield from chunks
  File "/home/anaconda3/envs/py35/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/home/anaconda3/envs/py35/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/home/anaconda3/envs/py35/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: 192 is not JSON serializable

What is this error?

**Comment by tensorboy** [comment]
Maybe you should change the preprocessing from `vgg` to `rtpose` for the original model.

**Comment by tensorboy** [comment]
VGG subtract the ImageNet mean but `rtpose` divided 255 and subtracting 0.5 for the image:https://github.com/tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation/blob/master/training/datasets/coco_data/preprocessing.py

**Comment by sobesshi** [comment]
Thanks a lot!

**Comment by qiuzhongwei-USTB** [comment]
> VGG subtract the ImageNet mean but rtpose divided 255 and subtracting 0.5 for the image:https://github.com/tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation/blob/master/training/datasets/coco_data/preprocessing.py

Hi, 
def vgg_preprocess(image):
    image = image.astype(np.float32) / 255.
    means = [0.485, 0.456, 0.406]
    stds = [0.229, 0.224, 0.225]

    preprocessed_img = image.copy()[:, :, ::-1]
    for i in range(3):
        preprocessed_img[:, :, i] = preprocessed_img[:, :, i] - means[i]
        preprocessed_img[:, :, i] = preprocessed_img[:, :, i] / stds[i]

    preprocessed_img = preprocessed_img.transpose((2, 0, 1)).astype(np.float32)
    return preprocessed_img

I think preprocessed_img = preprocessed_img.transpose((2, 0, 1)).astype(np.float32) should be preprocessed_img = preprocessed_img.transpose((2, 1, 0)).astype(np.float32)

or why you  change RGB image to BRG?
