### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by Sierkinhane** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#77]
MemoryError
the memory of my computer is 16G, it seems that it can't the dataloader. how can i solve this problem?

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "F:\Anaconda\anaconda3-5.2.0\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "F:\Anaconda\anaconda3-5.2.0\lib\multiprocessing\spawn.py", line 116, in _main
    self = pickle.load(from_parent)
MemoryError

**Comment by Sierkinhane** [comment]
okay! i try to reduce the num of workers, it effects!
