### ISSUE TITLE
Mobilenet not working

### ISSUE THREAD

**Issue by karthee320** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#87]
I am trying to run the demo/picture_demo.py code with mobilenet option. Going through the codes, I found there is an option to provide mobilenet model. But it seems the code is not fixed for mobilenet. Am I right? 

Traceback (most recent call last):
  File "demo/picture_demo.py", line 29, in <module>
    model = get_model('mobilenet')     
  File "/home/nvidia/Tracking/pytorch/pytorch_Realtime_Multi-Person_Pose_Estimation/network/rtpose_vgg.py", line 224, in get_model
    model = rtpose_model(models)
  File "/home/nvidia/Tracking/pytorch/pytorch_Realtime_Multi-Person_Pose_Estimation/network/rtpose_vgg.py", line 141, in __init__
    self.model0 = model_dict['block0']
KeyError: 'block0'

@tensorboy : Have you tried the mobilenet model for pose estimation?

**Comment by GreenTeaHua** [comment]
the same  question for me.
I guss, the pth model file just for vgg19,

**Comment by LIUHAO121** [comment]
you need write some codes in rtpose.py for mobilenet

**Comment by cwlinghk** [comment]
Where can I find the pretrained mobilenet models? Thank you very much.
