### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by Sugarbank** [tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation#9]
Hi I just want to run in cpu mode.Is it possible to set Cpu flags and avoid this error?
Tried setting Cpu mode from your feedback in the last issue but was unable to do so...Is it possible to add a flag for CPU mode?

Christians-iMac:pytorch_Realtime_Multi-Person_Pose_Estimation-master sugarbank$ python picture_demo.py
Traceback (most recent call last):
  File "picture_demo.py", line 153, in <module>
    imageToTest = Variable(T.transpose(T.transpose(T.unsqueeze(torch.from_numpy(oriImg).float(),0),2,3),1,2),volatile=True).cuda()
  File "/usr/local/lib/python2.7/site-packages/torch/autograd/variable.py", line 243, in cuda
    return CudaTransfer(device_id, async)(self)
  File "/usr/local/lib/python2.7/site-packages/torch/autograd/_functions/tensor.py", line 160, in forward
    return i.cuda(async=self.async)
  File "/usr/local/lib/python2.7/site-packages/torch/_utils.py", line 65, in _cuda
    return new_type(self.size()).copy_(self, async)
  File "/usr/local/lib/python2.7/site-packages/torch/cuda/__init__.py", line 272, in __new__
    _lazy_init()
  File "/usr/local/lib/python2.7/site-packages/torch/cuda/__init__.py", line 84, in _lazy_init
    _check_driver()
  File "/usr/local/lib/python2.7/site-packages/torch/cuda/__init__.py", line 51, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Christians-iMac:pytorch_Realtime_Multi-Person_Pose_Estimation-master sugarbank$

**Comment by tensorboy** [comment]
Variable(T.transpose(T.transpose(T.unsqueeze(torch.from_numpy(oriImg).float(),0),2,3),1,2),volatile=True).cuda()    

remove .cuda() here.

**Comment by Sugarbank** [comment]
That worked thanks:)
